name: Publish to gh-pages branch

on:
  push:
    branches:
      - main

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build, Generate Sitemap, and Deploy
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: blacklightpy/notes
          event-type: notes-update

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: vaultofknowledge

      - name: Install dependencies and build site
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/obsidian-html/obsidian-html
          obsidianhtml convert -i vaultofknowledge/config.yaml -v
          touch html/.nojekyll

      - name: Generate sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://blacklightpy.github.io/vaultofknowledge
          additional-extensions: jpg jpeg png webp gif
          exclude-paths: /not_created.html /index.html
          path-to-root: html   # generate sitemap inside build dir

      - name: Show sitemap stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./html
          commit_message: "Build: ${{ github.sha }} (with sitemap)"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./html

      - name: Deploy to GitHub Pages (official)
        id: deployment
        uses: actions/deploy-pages@v4

